language: node_js
node_js:
  - "6.10"
  - "4.4"
sudo: required
services:
  - docker
before_install:
  - docker pull localstack/localstack
  - docker run -d -p 4567-4582:4567-4582 -p 8080:8080 localstack/localstack
  - echo "127.0.0.1 localstack" | sudo tee -a /etc/hosts
script:
  - npm run test
  - npm run integ
